---
name: reviewdog
on: push

jobs:

  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: reviewdog/action-golangci-lint@v1.14.1
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "-c .golangci.yml"
          level: "error"
          reporter: github-check
